weights: yolov5s.pt
cfg: ./data/DOOR/yolo-obj.cfg
data: ./data/door.yaml
hyp: data/hyp.scratch.yaml
epochs: 30
batch_size: 4
img_size:
- 640
- 640
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: true
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
log_imgs: 16
log_artifacts: false
workers: 8
project: runs/train
name: yolov5s_door
exist_ok: false
quad: false
world_size: 1
global_rank: -1
save_dir: runs/train/yolov5s_door8
total_batch_size: 4
